name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: davidnjau21/r_docker_image
        tags: latest
        registry: docker.io
        dockerfile: Dockerfile
        username: davidnjau21
        password: Sc281-6736/2014
