name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Push to docker hub
      run: docker build -t davidnjau21/r_docker .
           echo "Sc281-6736/2014" | docker login -u "davidnjau21" --password-stdin
           docker push davidnjau21/r_docker:latest
           docker logout
